name: Docker Utility Deploy On Beast

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'beast/.env/utility/**'
      - 'beast/utility/**'
      - 'beast/utility.yml'

jobs:
  deploy:
    runs-on: [self-hosted, beast]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Update docker compose file for portainer
        run: |
          docker compose \
            --env-file "$HOME/.secrets/utility.env" \
            -f $GITHUB_WORKSPACE/beast/utility.yml \
            up -d